// react-codetest/src/components/Header.js
import React from 'react'

function Header(props) {
  const handleNewPostClick = (e) => {
    props.setPostModalDisplay(true);
  }

  return(
    <div id="header">
      <div id="logo">
        <img src="images/logo.png" alt="the network"/>
      </div>
      <div id="search">
        <form method="get" action="#">
          <input type="search" name="terms" placeholder="Search...."/>
          <input type="submit" value="Go"/>
        </form>
      </div>
      <div className="header-nav">
        <a href="/">Home</a>
        <button className="new-post-button" onClick={handleNewPostClick} >Post an update</button>
        <img className="header-user-pic" src={props.curUser.pic} alt="" />
      </div>
    </div>
  )
}

export default Header;

// codetest-angular/src/app/components/header/header.component.ts
import { Component, OnInit } from '@angular/core';

@Component({
  selector: 'app-header',
  templateUrl: './header.component.html',
  styleUrls: ['./header.component.scss']
})
export class HeaderComponent implements OnInit {
  showAddPostDialog = false;

  constructor() { }

  ngOnInit() {
  }

  showModal($event) {
    $event.preventDefault();
    this.showAddPostDialog = true;
  }

  hideModal() {
    this.showAddPostDialog = false;
  }

}

<div id="header">
  <div id="logo">
    <img src="assets/images/logo.png" alt="the network" />
  </div>
  <div id="search">
    <form method="get" action="#">
      <input type="search" name="terms" placeholder="Search...." />
      <input type="submit" value="Go" />
    </form>
  </div>
  <div id="nav">
    <a href="#">Home</a>
    <a href="#" (click)="showModal($event)">Post an update</a>
    <img class="user-image" src="assets/images/profile/daniel-craig.jpg" />
  </div>
</div>

<app-new-post-dialog *ngIf="showAddPostDialog" (dialogClosed)="hideModal()"></app-new-post-dialog>
